### ISSUE TITLE
Compatibility with Token Action HUD

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#9]
Token Action HUD is an indispensable and widely popular (>30% of users according to forge) 

In twilight, the area where options appear renders a black solid background and an HR separator on the line of the header. These should not be present. the container of the options in Token Action HUD is transparent. 

![image](https://user-images.githubusercontent.com/4083812/125762011-6c2ac0c4-2b0c-4d02-9570-b030276c57c9.png)

**Comment by Rayuaz** [comment]
Hey dude! Those are all by design. The opaque background jivess better with the whole interface, and helps focus on the information you are looking for. Ideally, you won't spend a lot of time on these menus, so I don't think the spatial awareness you get from the tranlscuscent background is very necessary. The HR is there to give some better visual separtion between the sections, without being too on your face and taking too much space. Feel free to disagree with me on any of these points.

**Comment by apoapostolov** [comment]
Good to know this is intentional and your thoughts behind it. I only disagree with the use of a HR tag, to be it doesn't fit there at all. I would still like it if the black background has some minor level of transparency like 15-25% to give it a dark glass feel... but it might be personal taste.

**Comment by Rayuaz** [comment]
Unless somebody else has a problem with it, I'll keep it as is. However, if you want to change it, you can add these custom CSS rules:

    #token-action-hud .tah-category.hover .tah-content .tah-subcategory .tah-subtitle:after {
        display: none;
    }

    #token-action-hud .tah-category.hover .tah-content {
        background: #191813cf!important;
    }

**Comment by apoapostolov** [comment]
@Rayuaz That is good for me. I suggest you open a GitHub wiki and document there all custom CSS people can use, such as this case.

**Comment by apoapostolov** [comment]
To be honest, now it really looks beautiful

![image](https://user-images.githubusercontent.com/4083812/125833341-3a9ae1f8-2c31-4348-950d-ec471f5365d3.png)
